export const DISCOVER_EVENTS = 'DISCOVER_EVENTS'
export const SEARCH_EVENTS = 'SEARCH_EVENTS'
export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM'
export const RESET_SEARCH_RESULTS = 'RESET_SEARCH_RESULTS'
